config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/faq'

  get 'static_pages/how_it_works'

  get 'static_pages/privacy'

  get 'static_pages/terms'

  get 'profiles/myprofile'

  get 'profiles/lawyerprofile'

devise_for :users


get 'questions/commercial'

  get 'questions/ip'

  get 'questions/show_all'

  get 'questions/employment'

  get 'questions/real_estate'

  get 'questions/venture_cap'

  match '/' => 'static_pages#home', via: [:get]

  match 'questions/commercial' => 'questions#commercial', via: [:get]

  match 'questions/ip' => 'questions#ip', via: [:get]
  match 'questions/employment' => 'questions#employment', via: [:get]
  match 'questions/real_estate' => 'questions#real_estate', via: [:get]
  match 'questions/venture_cap' => 'questions#venturecap', via: [:get]

  match 'search' => 'questions#search', via: [:get, :post], as: :search

resources :answers do
    resources :answercomments
  end

  resources :questions do 
    resources :questioncomments
  end

  resources :questions do
    resources :answers do
        member do
      put "like", to: "answers#upvote"
      put "dislike", to: "answers#downvote"
    end
  end
end

authenticated :user do
  root to: "questions#show_all", as: :authenticated_root
end
unauthenticated do
  root to: "static_pages#home", as: :unauthenticated_root
end
  

  
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :set_user, only: [:lawyerprofile]
  before_action :authenticate_user!, only: [:myprofile]


  def myprofile

  	@user = current_user
  	@questions = @user.questions.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  	@answers = @user.answers.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    @comments = @user.questioncomments.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    
  end

  def lawyerprofile
  	@answers = @user.answers.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end



    private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user])
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_is_not_lawyer.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-body" id="profile-header">
				<div class="col-md-3">
					<% if @user.image.exists? %>
         				<img><%= image_tag @user.image.url(:medium)%></img>
        			<%else%>
          				<img><%= image_tag "missing.png"%></img>     
       				<%end%>
				</div>

				<div class="col-md-4">
					<h2><strong> <%= @user.name %> </strong></h2>
					<h4> <%= @user.email %> </h4>
					<h4> <%= @user.company %> </h4>
					<h4>Industry: <%= @user.industry%> </h4>
					<%= link_to "Edit profile", edit_user_registration_path, class: "btn btn-warning" %>
				</div>

				<div class="col-md-4" id="stats-column">
					
					<h2>Number of questions: <%= @user.questions_count %></h2>
				</div>
				
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h4 align="center">Questions</h4>
				</div>
			</div>
			
			<% @questions.each do |question| %>
				<div class="well well-sm">
					<%= truncate(question.title, length: 350, omission: '.... (click "View" to see full question)') %>
					<h5><small>Created <%=question.created_at.to_formatted_s(:long) %></small><span class="categoryprofile"><%= link_to "#{question.category.name}", polymorphic_path([question.category.linkname])  %> </span><span class="upvotesinfo">Answers: <%= question.answers_count%></span></h5>
					<div class="row">
						<div class="col-md-12">
							<%= link_to "View", question_path(question), class: "btn btn-success btn-sm" %>
							<%= link_to "Edit", edit_question_path(id: question), class: "btn btn-warning btn-sm" %>
							
						</div>
					</div>
				</div>
			<%end%>	
		</div>
		
	</div>
</div>

app/views/profiles/_islawyer.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-body" id="profile-header">
				<div class="col-md-3">
					<% if @user.image.exists? %>
         				<img><%= image_tag @user.image.url(:medium)%></img>
        			<%else%>
          				<img><%= image_tag "missing.png"%></img>     
       				<%end%>
				</div>

				<div class="col-md-4">
					<h2><strong> <%= @user.name %> </strong></h2>
					<h4> <%= @user.email %> </h4>
					<h4> <%= @user.company %> </h4>
					<h4>SRA Number: <%= @user.SRA_number%> </h4>
					<%= link_to "Edit profile", edit_user_registration_path, class: "btn btn-warning" %>
				</div>

				<div class="col-md-4" id="stats-column">
					<h2>User score: <%= @user.karma %></h2>
					<h2>Number of answers: <%= @user.answers_count %></h2>
				</div>
				
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="col-md-4">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h4 align="center">Answers</h4>
				</div>
			</div>

			<% @answers.each do |answer| %>
				<div class="well well-sm">
					<p><%= truncate(answer.body, length: 120, omission: '.... (click "View" to see full answer)') %></p>
					<h5><small>Created <%=answer.created_at.to_formatted_s(:long) %></small><span class="categoryprofile"><%= link_to "#{answer.question.category.name}", polymorphic_path([answer.question.category.linkname])  %> </span> <span class="upvotesinfo">Upvotes: <%= answer.get_upvotes.size%></span></h5>
					<div class="row">
						<div class="col-md-12">
							<%= link_to "View", question_path(id: answer.question), class: "btn btn-success btn-sm" %>
							<%= link_to 'Delete Answer', question_answer_path(answer.question, answer), method: :delete, class: "btn btn-danger btn-sm" %>
						</div>
					</div> 
				</div>
			<%end%>
		</div>

		<div class="col-md-4">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h4 align="center">Questions</h4>
				</div>
			</div>
			
			<% @questions.each do |question| %>
				<div class="well well-sm">
					<%= truncate(question.title, length: 150, omission: '.... (click "View" to see full question)') %>
					<h5><small>Created <%=question.created_at.to_formatted_s(:long) %></small><span class="categoryprofile"><%= link_to "#{question.category.name}", polymorphic_path([question.category.linkname])  %> </span><span class="upvotesinfo">Answers: <%= question.answers_count%></span></h5>
					<div class="row">
						<div class="col-md-12">
							<%= link_to "View", question_path(question), class: "btn btn-success btn-sm" %>
							<%= link_to "Edit", edit_question_path(id: question), class: "btn btn-warning btn-sm" %>
							
						</div>
					</div>
				</div>
			<%end%>	
		</div>

		<div class="col-md-4">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h4 align="center">Comments</h4>
				</div>

			</div>

			<% @comments.each do |comment| %>
				<div class="well well-sm">
					<%= truncate(comment.body, length: 120, omission: '.... (click "View" to see full comment)') %>
					<h5><small>Question created <%=comment.created_at.to_formatted_s(:long) %></small><span class="categoryprofile"><%= link_to "#{comment.question.category.name}", polymorphic_path([comment.question.category.linkname])  %> </span></h5>
					<div class="row">
						<div class="col-md-12">
							<%= link_to "View", question_path(id: comment.question), class: "btn btn-success btn-sm" %>
							<%= link_to 'Delete Comment', question_questioncomment_path(comment.question, comment), method: :delete, class: "btn btn-danger btn-sm" %>						
						</div>	
					</div>
				</div>
			<%end%>
		</div>
		
	</div>
</div>

app/views/profiles/lawyerprofile.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-body" id="profile-header">
				<div class="col-md-3">
					<% if @user.image.exists? %>
         				<img><%= image_tag @user.image.url(:medium)%></img>
        			<%else%>
          				<img><%= image_tag "missing.png"%></img>     
       				<%end%>
				</div>

				<div class="col-md-4">
					<h2><strong> <%= @user.name %> </strong></h2>
					<h4> <%= @user.email %> </h4>
					<h4> <%= @user.company %> </h4>
					<h4>SRA Number: <%= @user.SRA_number%> </h4>
					<%= link_to "Edit profile", edit_user_registration_path, class: "btn btn-warning" if current_user == @user %>
				</div>

				<div class="col-md-4" id="stats-column">
					<h2>User score: <%= @user.karma %></h2>
					<h2>Number of answers: <%= @user.answers_count %></h2>
				</div>
				
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h4 align="center">Answers</h4>
				</div>
			</div>
			
			<% @answers.each do |answer| %>
				<div class="well well-sm">
					<p><%= truncate(answer.body, length: 300, omission: '.... (click "View" to see full answer)') %></p>
					<h5><small>Created <%=answer.created_at.to_formatted_s(:long) %></small><span class="categoryprofile"><%= link_to "#{answer.question.category.name}", polymorphic_path([answer.question.category.linkname])  %> </span> <span class="upvotesinfo">Upvotes: <%= answer.get_upvotes.size%></span></h5>
					<div class="row">
						<div class="col-md-12">
							<%= link_to "View", question_path(id: answer.question), class: "btn btn-success btn-sm" %>
								
						</div>
					</div> 
				</div>
			<%end%>	
		</div>
		
	</div>
</div>

app/views/profiles/myprofile.html.erb
<% if current_user.is_solicitor == true %>

<%= render 'profiles/islawyer' %>

<%else%>

<%= render 'profiles/is_not_lawyer'%>

<%end%>