config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/faq'

  get 'static_pages/how_it_works'

  get 'static_pages/privacy'

  get 'static_pages/terms'

  get 'profiles/myprofile'

  get 'profiles/lawyerprofile'

devise_for :users


get 'questions/commercial'

  get 'questions/ip'

  get 'questions/show_all'

  get 'questions/employment'

  get 'questions/real_estate'

  get 'questions/venture_cap'

  match '/' => 'static_pages#home', via: [:get]

  match 'questions/commercial' => 'questions#commercial', via: [:get]

  match 'questions/ip' => 'questions#ip', via: [:get]
  match 'questions/employment' => 'questions#employment', via: [:get]
  match 'questions/real_estate' => 'questions#real_estate', via: [:get]
  match 'questions/venture_cap' => 'questions#venturecap', via: [:get]

  match 'search' => 'questions#search', via: [:get, :post], as: :search

resources :answers do
    resources :answercomments
  end

  resources :questions do 
    resources :questioncomments
  end

  resources :questions do
    resources :answers do
        member do
      put "like", to: "answers#upvote"
      put "dislike", to: "answers#downvote"
    end
  end
end

authenticated :user do
  root to: "questions#show_all", as: :authenticated_root
end
unauthenticated do
  root to: "static_pages#home", as: :unauthenticated_root
end
  

  
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	acts_as_votable
	
	belongs_to :question, counter_cache: true
	belongs_to :user, counter_cache: true
	has_many :answercomments, dependent: :destroy

	validates :body, :presence => true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index] 
  before_action :correct_user, only: [:edit, :update, :destroy]


  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new
    @answer.user = current_user
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create

    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
        AnswerMailer.answer_confirm(@question, @answer).deliver_now
      else
        format.html { redirect_to @question, notice: 'You cannot submit a blank answer, please try again.' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Answer was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def upvote
      @question = Question.find(params[:question_id])
      @answer = @question.answers.find(params[:id])
      if current_user.voted_for? @answer
        flash[:notice] = "You cannot vote more than once"
      
      else
      @answer.upvote_by current_user 
      @answer.user.increase_karma
      @answer.question.increase_tally
      flash[:success] = "You've upvoted"
      AnswerMailer.upvote_confirm(@question, @answer.user).deliver_now 
      end
      
      redirect_to @question       
    end

  def downvote
      @question = Question.find(params[:question_id])
      @answer = @question.answers.find(params[:id])
      if current_user.voted_for? @answer
      flash[:notice] = "You cannot vote more than once"
      else
      @answer.downvote_by current_user
      @answer.user.decrease_karma
      flash[:success] = "You've downvoted"
    end
      
      redirect_to @question     
      
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def correct_user
      @answer = current_user.answers.find_by(id: params[:id])
      redirect_to questions_path, notice: "Not authorized to edit this answer" if @answer.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:body, :post_id, :user_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<div class="form-group">
<%= form_for [@question, Answer.new] do |f| %>

  <div class="field">
    <%= f.label :body, "Post an answer" %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  
  
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>
</div>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing Answers</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.body %></td>
        <td><%= answer.question_id %></td>
        <td><%= answer.user_id %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @answer.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user_id %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>