config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/faq'

  get 'static_pages/how_it_works'

  get 'static_pages/privacy'

  get 'static_pages/terms'

  get 'profiles/myprofile'

  get 'profiles/lawyerprofile'

devise_for :users


get 'questions/commercial'

  get 'questions/ip'

  get 'questions/show_all'

  get 'questions/employment'

  get 'questions/real_estate'

  get 'questions/venture_cap'

  match '/' => 'static_pages#home', via: [:get]

  match 'questions/commercial' => 'questions#commercial', via: [:get]

  match 'questions/ip' => 'questions#ip', via: [:get]
  match 'questions/employment' => 'questions#employment', via: [:get]
  match 'questions/real_estate' => 'questions#real_estate', via: [:get]
  match 'questions/venture_cap' => 'questions#venturecap', via: [:get]

  match 'search' => 'questions#search', via: [:get, :post], as: :search

resources :answers do
    resources :answercomments
  end

  resources :questions do 
    resources :questioncomments
  end

  resources :questions do
    resources :answers do
        member do
      put "like", to: "answers#upvote"
      put "dislike", to: "answers#downvote"
    end
  end
end

authenticated :user do
  root to: "questions#show_all", as: :authenticated_root
end
unauthenticated do
  root to: "static_pages#home", as: :unauthenticated_root
end
  

  
  
end

app/models/questioncomment.rb
class Questioncomment < ActiveRecord::Base
	belongs_to :question, counter_cache: true
	belongs_to :user

	validates :body, :presence => true
end

app/controllers/questioncomments_controller.rb
class QuestioncommentsController < ApplicationController
  before_action :set_questioncomment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /questioncomments
  # GET /questioncomments.json
  def index
    @questioncomments = Questioncomment.all
  end

  # GET /questioncomments/1
  # GET /questioncomments/1.json
  def show
  end

  # GET /questioncomments/new
  def new
    @question = Question.find(params[:question_id])
    @questioncomment = @question.questioncomments.new
    @questioncomment.user = current_user
  end

  # GET /questioncomments/1/edit
  def edit
  end

  # POST /questioncomments
  # POST /questioncomments.json
  def create
    @question = Question.find(params[:question_id])
    @questioncomment = @question.questioncomments.new(questioncomment_params)
    @questioncomment.user = current_user

    respond_to do |format|
      if @questioncomment.save
        format.html { redirect_to @question, notice: 'Comment successfully posted.' }
        format.json { render :show, status: :created, location: @questioncomment }
        CommentMailer.questioncomment_confirm(@question, @questioncomment).deliver_now
        
      else
        format.html { render :new }
        format.json { render json: @questioncomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questioncomments/1
  # PATCH/PUT /questioncomments/1.json
  def update
    respond_to do |format|
      if @questioncomment.update(questioncomment_params)
        format.html { redirect_to @questioncomment, notice: 'Questioncomment was successfully updated.' }
        format.json { render :show, status: :ok, location: @questioncomment }
      else
        format.html { render :edit }
        format.json { render json: @questioncomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questioncomments/1
  # DELETE /questioncomments/1.json
  def destroy
    @questioncomment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questioncomment
      @questioncomment = Questioncomment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questioncomment_params
      params.require(:questioncomment).permit(:body, :question_id, :user_id)
    end
end

app/helpers/questioncomments_helper.rb
module QuestioncommentsHelper
end

app/views/questioncomments/_form.html.erb
	<div class="form-group">
	<%= form_for [@question, Questioncomment.new] do |f| %>
	 
	  <div class="form-group">
	    <%= f.label :body, "Post a comment on this question" %><br>
	    <%= f.text_area :body, class: "form-control" %>
	  </div>
	  
	  <div class="actions">
	    <%= f.submit "Post comment", class: "btn btn-primary"  %>
	  </div>
	<% end %>

	<small>NOTE: the original poster or non-lawyer users will remain anonymous if commenting</small><br>
	<br>
	<small>Comments from lawyers will not be anonymous</small>
	</div>
	<hr>

app/views/questioncomments/_questioncomments.html.erb
<% @question.questioncomments.each do |questioncomments| %>
<div class="well well-sm">
    <%= questioncomments.body %><br>
    <small><i>posted at <%= questioncomments.created_at.to_formatted_s(:long)%> by 
		
		<% if questioncomments.user == questioncomments.question.user %>
		<%= "the Original Poster"%>

		<%elsif questioncomments.user != questioncomments.question.user && questioncomments.user.is_solicitor? == true %>

		<%= questioncomments.user.name %>

		<%elsif questioncomments.user != questioncomments.question.user && questioncomments.user.is_solicitor? == false %>

		<%= "another Lawreo user (non-lawyer)" %>

		<%end%>


    	</i></small>
</div>
 <%end%>

app/views/questioncomments/edit.html.erb
<h1>Editing Questioncomment</h1>

<%= render 'form' %>

<%= link_to 'Show', @questioncomment %> |
<%= link_to 'Back', questioncomments_path %>

app/views/questioncomments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questioncomments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Question</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questioncomments.each do |questioncomment| %>
      <tr>
        <td><%= questioncomment.body %></td>
        <td><%= questioncomment.question_id %></td>
        <td><%= questioncomment.user_id %></td>
        <td><%= link_to 'Show', questioncomment %></td>
        <td><%= link_to 'Edit', edit_questioncomment_path(questioncomment) %></td>
        <td><%= link_to 'Destroy', questioncomment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Questioncomment', new_questioncomment_path %>

app/views/questioncomments/new.html.erb
<h1>New Questioncomment</h1>

<%= render 'form' %>

<%= link_to 'Back', questioncomments_path %>

app/views/questioncomments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @questioncomment.body %>
</p>

<p>
  <strong>Question:</strong>
  <%= @questioncomment.question_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @questioncomment.user_id %>
</p>

<%= link_to 'Edit', edit_questioncomment_path(@questioncomment) %> |
<%= link_to 'Back', questioncomments_path %>