config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/faq'

  get 'static_pages/how_it_works'

  get 'static_pages/privacy'

  get 'static_pages/terms'

  get 'profiles/myprofile'

  get 'profiles/lawyerprofile'

devise_for :users


get 'questions/commercial'

  get 'questions/ip'

  get 'questions/show_all'

  get 'questions/employment'

  get 'questions/real_estate'

  get 'questions/venture_cap'

  match '/' => 'static_pages#home', via: [:get]

  match 'questions/commercial' => 'questions#commercial', via: [:get]

  match 'questions/ip' => 'questions#ip', via: [:get]
  match 'questions/employment' => 'questions#employment', via: [:get]
  match 'questions/real_estate' => 'questions#real_estate', via: [:get]
  match 'questions/venture_cap' => 'questions#venturecap', via: [:get]

  match 'search' => 'questions#search', via: [:get, :post], as: :search

resources :answers do
    resources :answercomments
  end

  resources :questions do 
    resources :questioncomments
  end

  resources :questions do
    resources :answers do
        member do
      put "like", to: "answers#upvote"
      put "dislike", to: "answers#downvote"
    end
  end
end

authenticated :user do
  root to: "questions#show_all", as: :authenticated_root
end
unauthenticated do
  root to: "static_pages#home", as: :unauthenticated_root
end
  

  
  
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <a class="navbar-brand" href="/questions/show_all">Lawreo - <small><i>Your free legal Q&A site</i></small></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
        <li><%= link_to "Home", static_pages_home_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "My profile", profiles_myprofile_path %> </li>
        
        <%else%>
        <li><%= link_to "Home", static_pages_home_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
        <%end%>
       
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_subnav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Browse questions by Category <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Commercial", questions_commercial_path  %></li>
            <li><%= link_to "Intellectual Property", questions_ip_path %></li>
            <li><%= link_to "Employment", questions_employment_path %></li>
            <li><%= link_to "Real Estate", questions_real_estate_path %></li>
            <li><%= link_to "Venture Capital", questions_venture_cap_path %></li>
            <li class="divider"></li>
            <li><%= link_to "View all", questions_show_all_path%></li>
          </ul>
        </li>
      </ul>
      
      <div class="navbar-form navbar-right" role="search" id="searchitem">
        <div class="form-group">
          <div class="form-group" id="searchbar">
          <%= form_tag search_path method: :get do %>
          <%= search_field_tag :q, nil, :placeholder => "Search" , class: "form-control"%>
          <%= submit_tag "Submit", class: "btn btn-default"%>
          <%end%>
          </div>
        </div> 
      </div>
      
      <div class="navbar-form navbar-right">
        <ul class="nav navbar-nav navbar-right">
          <%= link_to "Ask a question", new_question_path, class: "btn btn-warning"%> 
        </ul>
      </div>
      
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lawreo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
   <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div id="wrapper">
	<header>
	<%= render 'layouts/header' %>
	<%= render 'layouts/subnav' unless @disable_nav %>
      

		<div id="alertmsg">
		      <% flash.each do |name, msg| %>
					<%= content_tag(:div, msg, class: "alert alert-dismissable alert-info") %>
				<% end %>
		</div>
	</header>
	
    <div class="container">    
		<%= yield %>
	</div>
</div>
<br>
<br>
<div id="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="col-md-6" id="footer-col">

					<br>
					<p> <%= link_to "About", static_pages_about_path %> | <%= link_to "FAQ", static_pages_faq_path  %> | <%= link_to "Privacy Policy", static_pages_privacy_path  %> | <%= link_to "Terms", static_pages_terms_path %> | </p>
					
					
				</div>

				<div class="col-md-6">
					<div id="footer-text">
						<br>
						<p><small>Lawreo © 2015. All Rights Reserved.</a></small></p>
						<p><small>Contact: hello@lawreo.com</small></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

</body>
</html>